spring:
  datasource:
#    EXTERNAL DATABASE

#    url: jdbc:postgresql://ep-royal-fog-a2dwl67l.eu-central-1.aws.neon.tech:5432/VM-com2
#    username: VM-com
#    password: hpIBGdv9j6CE
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#
#    LOCAL DOCKER DATABASE
#    password: vmcom_secret_password
#    url: jdbc:postgresql://127.0.0.1:5432/vmcom_db
#    username: vmcom
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


application:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
    jwt:
      secret-key: 42285f5c5975375d20587e57565476356420274b433a767c5e6d4b503a
      # 4 hours
      expiration: ${ACCESS_TOKEN_EXPIRATION_TIME:1440000}
      refresh-token:
        # 7 days
        expiration: ${REFRESH_TOKEN_EXPIRATION_TIME:604800000}