version: "3.9"
services:
  vmcom_app-database:
    image: postgres
    container_name: vmcom_app-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - '5433:5432'
    networks:
      - vmcom_network
    restart: always

networks:
  vmcom_network:
    driver: bridge
